name:"podcast Generator"
author:"Abdelrahman"
description:"Generates a feed for podcast from a Yaml file"
runs:
  using:"docker"
  image: "Dockerfile"
branding:
  icon:"git-branch"
  colour:"red"
inputs:
  email:
    description: the comiter's email address
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: the comiter's name
    required: true
    default: ${{github.actor}}
